title: Anton Richardt

description: Work from Anton Richardt Senior VFX Artist @Tuatara Games.

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

url: https://arfx.github.io/webpage/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://arfx.github.io/webpage/